In [1]:
import numpy as np
#1
array = np.arange(10, 50)
print(array)
#2
array2 = np.arange(0, 9).reshape(3, 3)
print(array2)

#3
array3 = np.eye(3, 3)
print(array3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
np.random.rand(3, 3, 3)

array([[[0.75785915, 0.24431915, 0.4444428 ],
        [0.07771439, 0.61347885, 0.41145224],
        [0.98570233, 0.02403399, 0.26403069]],

       [[0.03734698, 0.58603915, 0.80905889],
        [0.36205401, 0.76945072, 0.27088987],
        [0.63819486, 0.38991001, 0.40649597]],

       [[0.98464267, 0.00234734, 0.69441266],
        [0.66408914, 0.67164992, 0.88609726],
        [0.61390612, 0.87675345, 0.56595127]]])

In [3]:
array5 = np.random.rand(10, 10)
print(array5.min())
array5.max()

0.015624184410499065


np.float64(0.9904757192913981)

In [4]:
array6 = np.random.rand(30)
print(array6.mean())

0.5518317297553761


In [6]:
array7 = np.random.rand(5, 5)
norm = (array7 - array7.mean())/(array7.max()-array7.min())
norm

array([[ 0.47154843, -0.07859618,  0.32316062, -0.02493984,  0.31185774],
       [-0.39442947,  0.27003509, -0.28259365,  0.4612363 , -0.44429869],
       [ 0.05215403, -0.34674051, -0.39966771, -0.42682668, -0.12890882],
       [ 0.38603323,  0.07663688, -0.10166061, -0.12261729,  0.55570131],
       [-0.06009624,  0.13367281, -0.24994238,  0.0547491 , -0.03546748]])

In [7]:
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
result = np.dot(matrix1, matrix2)
result

array([[0.17435706, 0.88947091],
       [0.68717528, 0.94946287],
       [0.58083658, 1.23117369],
       [0.61785095, 1.15633268],
       [0.78724935, 1.24616643]])

In [13]:
matrix3 = np.random.rand(3, 3)
matrix4 = np.random.rand(3, 3)
np.dot(matrix4, matrix3)

array([[0.47858431, 0.51228682, 0.38094489],
       [0.40989063, 0.71499441, 0.49178197],
       [1.19904535, 1.37978579, 0.60468655]])

In [14]:
matrix5 = np.arange(16).reshape(4, 4)
matrix5.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [16]:
np.linalg.det(matrix3)

np.float64(0.12078442653696249)

In [17]:
matrix_A = np.random.rand(3, 4)
matrix_B = np.random.rand(4, 3)

result = np.dot(matrix_A, matrix_B)
result

array([[0.76872834, 1.27564268, 0.57215758],
       [0.86328749, 1.42527507, 0.62165488],
       [1.24822326, 1.85145303, 0.90093679]])

In [21]:
matrix = np.random.randint(1, 10, (3, 3))
vector = np.random.randint(1, 10, (3, 1))

product = np.dot(matrix, vector)



In [22]:
np.linalg.solve(matrix, vector)

array([[-0.10283688],
       [ 0.31560284],
       [ 0.93971631]])

In [26]:
matrix6 = np.random.randint(1, 26, (5, 5))
#print(matrix6)
print(matrix6.sum(axis=0))
print(matrix6.sum(axis=1))

[81 60 68 90 94]
[70 59 90 88 86]
